### ISSUE TITLE
Missing property definitions in ViewList.ts

### ISSUE THREAD

**Issue by esfand** [esfand/frzrts#1]
To make TypeScript happy the following field definitions must be explicitly added to the class:
I'm not sure about their exact type.

this.key
this.View
this.parent

I guest the type of key is string, the typeof view is view, and the type of parent is view.  No?

**Comment by esfand** [comment]
I think `parent` must be one of the common fields between View and ViewList and therefore must be defined in ExtendableObserver class.  Just a guess.

**Comment by pakastin** [comment]
Yes, parent is common property..

Key is a string. View is, well, View. parent is also View.

**Comment by esfand** [comment]
Thanks.
